alts_fit_filters: (residential_units > 0) & (large_area_id == 161)
alts_predict_filters: (vacant_residential_units > 0) & (large_area_id == 161)
choice_column: null
choice_mode: aggregate
choosers_fit_filters: (building_id > 1) & (hh_type_large_area_id == 60161)
choosers_predict_filters: hh_type_large_area_id == 60161
estimation_sample_size: 2000
fit_parameters:
  Coefficient: {st_b_ln_residential_units: 0.38292996338028823, st_b_ln_sqft_per_unit: -0.9440455173354441,
    st_jobs_within_30_min: -0.13454880229392424, st_zones_ln_empden: -0.06589048068627996,
    st_zones_ln_popden: 0.19313602552396586, st_zones_mean_age_of_head: -0.298490528035172,
    st_zones_mean_hh_size: 0.08394638953934169, st_zones_prop_hh_with_children: 0.15827582101172033,
    st_zones_prop_income_1: 0.5443857735069841, st_zones_prop_race_4: -0.10666361780687916}
  Std. Error: {st_b_ln_residential_units: 0.007175712717117953, st_b_ln_sqft_per_unit: 0.10334679703140774,
    st_jobs_within_30_min: 0.03323551586179815, st_zones_ln_empden: 0.030108370686748955,
    st_zones_ln_popden: 0.03621332169758026, st_zones_mean_age_of_head: 0.026368532247910935,
    st_zones_mean_hh_size: 0.03468260638602018, st_zones_prop_hh_with_children: 0.03618418496695594,
    st_zones_prop_income_1: 0.02615673524628894, st_zones_prop_race_4: 0.024984881692825565}
  T-Score: {st_b_ln_residential_units: 53.36472883965844, st_b_ln_sqft_per_unit: -9.134734161606795,
    st_jobs_within_30_min: -4.048344032131557, st_zones_ln_empden: -2.18844391720204,
    st_zones_ln_popden: 5.333286659999241, st_zones_mean_age_of_head: -11.319952329118362,
    st_zones_mean_hh_size: 2.420417560462777, st_zones_prop_hh_with_children: 4.3741712340974575,
    st_zones_prop_income_1: 20.81245110986167, st_zones_prop_race_4: -4.269126390840896}
fitted: true
interaction_predict_filters: null
log_likelihoods: {convergence: -11639.31954849863, 'null': -13815.510557964428, ratio: 0.1575179578297421}
model_expression: [st_b_ln_residential_units, st_b_ln_sqft_per_unit, st_jobs_within_30_min,
  st_zones_ln_popden, st_zones_ln_empden, st_zones_prop_income_1, st_zones_mean_age_of_head,
  st_zones_mean_hh_size, st_zones_prop_hh_with_children, st_zones_prop_race_4]
model_type: discretechoice
name: MNLDiscreteChoiceModel
prediction_sample_size: null
probability_mode: single_chooser
sample_size: 1000
