alts_fit_filters: (residential_units > 0) & (large_area_id == 115)
alts_predict_filters: (vacant_residential_units > 0) & (large_area_id == 115)
choice_column: null
choice_mode: aggregate
choosers_fit_filters: (building_id > 1) & (hh_type_large_area_id == 90115)
choosers_predict_filters: hh_type_large_area_id == 90115
estimation_sample_size: 2000
fit_parameters:
  Coefficient: {st_b_ln_residential_units: 0.4568731128099725, st_b_ln_sqft_per_unit: -0.6272927635568899,
    st_zones_empden: -0.02553163089894769, st_zones_households: 0.023087673485980873,
    st_zones_mean_age_of_head: -0.33865444829642843, st_zones_mean_hh_size: -0.2728527617020102,
    st_zones_prop_income_2: 0.08199162847014654, st_zones_prop_income_3: 0.27044568685072956,
    st_zones_prop_race_1: 0.20043050641330484, st_zones_prop_race_3: -0.001726241691548935}
  Std. Error: {st_b_ln_residential_units: 0.006261704227033783, st_b_ln_sqft_per_unit: 0.0989998397092144,
    st_zones_empden: 0.013277494620079792, st_zones_households: 0.02117599034226555,
    st_zones_mean_age_of_head: 0.020011972328577054, st_zones_mean_hh_size: 0.027431303682332684,
    st_zones_prop_income_2: 0.026566545180734823, st_zones_prop_income_3: 0.026776124455843944,
    st_zones_prop_race_1: 0.03337274916644302, st_zones_prop_race_3: 0.03415637658252177}
  T-Score: {st_b_ln_residential_units: 72.96306185103808, st_b_ln_sqft_per_unit: -6.336300800075989,
    st_zones_empden: -1.9229253431845303, st_zones_households: 1.0902759735349783,
    st_zones_mean_age_of_head: -16.922592273067988, st_zones_mean_hh_size: -9.946766105678853,
    st_zones_prop_income_2: 3.086273654039297, st_zones_prop_income_3: 10.100255072264734,
    st_zones_prop_race_1: 6.00581346815868, st_zones_prop_race_3: -0.050539368172684736}
fitted: true
interaction_predict_filters: null
log_likelihoods: {convergence: -10836.115059468828, 'null': -13815.510557964428, ratio: 0.21565583740066885}
model_expression: [st_b_ln_residential_units, st_b_ln_sqft_per_unit, st_zones_empden,
  st_zones_households, st_zones_prop_income_3, st_zones_prop_income_2, st_zones_mean_age_of_head,
  st_zones_mean_hh_size, st_zones_prop_race_1, st_zones_prop_race_3]
model_type: discretechoice
name: MNLDiscreteChoiceModel
prediction_sample_size: null
probability_mode: single_chooser
sample_size: 1000
