alts_fit_filters: (residential_units > 0) & (large_area_id == 5)
alts_predict_filters: (vacant_residential_units > 0) & (large_area_id == 5)
choice_column: null
choice_mode: aggregate
choosers_fit_filters: (building_id > 1) & (hh_type_large_area_id == 160005)
choosers_predict_filters: hh_type_large_area_id == 160005
estimation_sample_size: 2000
fit_parameters:
  Coefficient: {st_b_ln_building_sqft: 0.20953124549597957, st_b_ln_residential_units: 0.17938710207352085,
    st_b_ln_sqft_per_unit: 0.46009659083727017, st_zones_logsum_pop_high_income: 0.18250884509886656,
    st_zones_mean_age_of_head: 0.38134615164716573, st_zones_mean_hh_size: 0.07055989251594262,
    st_zones_prop_income_4: 0.3867259562013267, st_zones_prop_race_1: -0.035803560884833475,
    st_zones_sum_residential_units: 0.06604477402846864}
  Std. Error: {st_b_ln_building_sqft: 0.052946614391649466, st_b_ln_residential_units: 0.028833786555040295,
    st_b_ln_sqft_per_unit: 0.08977668209413371, st_zones_logsum_pop_high_income: 0.031218991489579455,
    st_zones_mean_age_of_head: 0.0306134663602781, st_zones_mean_hh_size: 0.03005796790294182,
    st_zones_prop_income_4: 0.031105664644787975, st_zones_prop_race_1: 0.034850110467628724,
    st_zones_sum_residential_units: 0.023917507655908575}
  T-Score: {st_b_ln_building_sqft: 3.957405924882442, st_b_ln_residential_units: 6.221420198526199,
    st_b_ln_sqft_per_unit: 5.124900810600733, st_zones_logsum_pop_high_income: 5.846083950526907,
    st_zones_mean_age_of_head: 12.456810579999326, st_zones_mean_hh_size: 2.3474605051074264,
    st_zones_prop_income_4: 12.43265368599433, st_zones_prop_race_1: -1.0273586053074462,
    st_zones_sum_residential_units: 2.761356867890579}
fitted: true
interaction_predict_filters: null
log_likelihoods: {convergence: -13188.53469345828, 'null': -13815.510557964428, ratio: 0.04538202637358968}
model_expression: [st_b_ln_residential_units, st_b_ln_building_sqft, st_b_ln_sqft_per_unit,
  st_zones_sum_residential_units, st_zones_prop_income_4, st_zones_mean_age_of_head,
  st_zones_logsum_pop_high_income, st_zones_mean_hh_size, st_zones_prop_race_1]
model_type: discretechoice
name: MNLDiscreteChoiceModel
prediction_sample_size: null
probability_mode: single_chooser
sample_size: 1000
