alts_fit_filters: (non_residential_sqft>0) & (large_area_id == 93)
alts_predict_filters: large_area_id == 93
choice_column: building_id
choice_mode: aggregate
choosers_fit_filters: (building_id > 0) (slid == 1600093) & (home_based_status ==
  0))
choosers_predict_filters: (slid == 1600093) & (home_based_status == 0)
estimation_sample_size: 5000
fit_parameters:
  Coefficient: {st_b_ln_non_residential_sqft: 1.5033593368700806, st_building_age: -0.31251371010249307,
    st_building_type_id_is_26: 0.14949252048107373, st_is_retail: 0.301733477265349,
    st_jobs_within_30_min: 0.005163061810438842, st_stories: 0.0027355944198807457,
    st_zones_ln_empden_16: 0.15993969005439768, st_zones_popden: -0.08410847274324895}
  Std. Error: {st_b_ln_non_residential_sqft: 0.008826759813287822, st_building_age: 0.017763890153670938,
    st_building_type_id_is_26: 0.0022718758001248904, st_is_retail: 0.0069346023388722165,
    st_jobs_within_30_min: 0.019032476036827135, st_stories: 0.002498266122365986,
    st_zones_ln_empden_16: 0.005240575045721491, st_zones_popden: 0.01443336978089522}
  T-Score: {st_b_ln_non_residential_sqft: 170.31836921708467, st_building_age: -17.59263919102267,
    st_building_type_id_is_26: 65.80136135648603, st_is_retail: 43.51128767311844,
    st_jobs_within_30_min: 0.271276411983838, st_stories: 1.0949972044171168, st_zones_ln_empden_16: 30.519492357041162,
    st_zones_popden: -5.827362148968111}
fitted: true
interaction_predict_filters: null
log_likelihoods: {convergence: -9944.176854439222, 'null': -17002.58571092777, ratio: 0.4151373783078196}
model_expression: [st_is_retail, st_building_type_id_is_26, st_stories, st_b_ln_non_residential_sqft,
  st_zones_ln_empden_16, st_jobs_within_30_min, st_zones_popden, st_building_age]
model_type: discretechoice
name: MNLDiscreteChoiceModel
prediction_sample_size: null
probability_mode: single_chooser
sample_size: 30
